name: CI

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    ubuntu:
        # This job runs directly on the Ubuntu host provided by GitHub Actions
        runs-on: ubuntu-latest

        # All of these steps run from within the main source
        # directory, so think of that as your $PWD
        steps:
            # This means clone the git repo
            - uses: actions/checkout@v2

            # Within the container, install the build dependencies and
            # test suite dependencies
            - name: Install Build Dependencies
              run: |
                  sudo apt-get update
                  sudo apt-get -y install make gcc autoconf

            # Compile the software
            - name: Build
              run: |
                  autoreconf -f -i
                  ./configure --with-xz --with-zlib --with-openssl
                  make

            # Run the test suite
            - name: Test
              run: make check
