name: CI

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    ubuntu:
        # This job runs directly on the Ubuntu host provided by GitHub Actions
        runs-on: ubuntu-latest

        # All of these steps run from within the main source
        # directory, so think of that as your $PWD
        steps:
            # This means clone the git repo
            - uses: actions/checkout@v2

            # Within the container, install the build dependencies and
            # test suite dependencies
            - name: Install Build Dependencies
              run: |
                  sudo apt-get update
                  sudo apt-get -y install make gcc autoconf automake gettext gtk-doc-tools python3-dev python3-pip lcov
                  sudo pip3 install cython gcovr
                  sudo apt-get -y install linux-headers-$(uname -r)

            # Compile the software
            - name: Build
              run: |
                  gtkdocize --docdir libkmod/docs || touch libkmod/docs/gtk-doc.make
                  autoreconf -f -i
                  ./configure --enable-debug --enable-python --with-xz --with-zlib --with-openssl --enable-coverage
                  make V=1

            # Run the test suite
            - name: Test
              run: |
                  make V=1 check
                  cat testsuite/test-suite.log

            # Generate code coverage reports
            - name: Coverage
              run: |
                  make coverage
                  curl -s https://codecov.io/bash | bash
